In [ ]:
import torch

# CON2D OUTPUT SHAPE CALCULATION = [(input_shape - filter_size + 2*Padding)/stride] + 1.
# if result of this value above is NOT a integer value, you will rounded to it's floor value. for instance 2.5 => 2

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, device=device, requires_grad=True)

print(tensor)
print(tensor.dtype)
print(tensor.device) # cuda:0 means you working on your first GPU that has CUDA.
print(tensor.requires_grad)

### Other Inıt Methods

In [ ]:
empty_tensor = torch.empty(size = (3,3)) # hafızada yer tutmayan istenen şekillerde random bir tensor olusturur, np.zeros ile karıstırılmamalıdır! 0 içeren bir tensor olusturmaz.
empty_tensor

zero_tensor = torch.zeros((3, 3)) # istenen şekilde 0 içeren tensor 
zero_tensor

rand_tensor = torch.rand((3, 3)) # istenen şekilde random değer içeren tensor. [0,1) arasında değerler üretir.
rand_tensor

rand_tensor = torch.randn((3, 3)) # istenen şekilde random değer içeren tensor ortalaması 0, varyansı 1 olan değerler üretir, bu yüzden negatif değer üretebilir.
randn_tensor

ones_tensor = torch.ones((3, 3))
ones_tensor

eye_tensor = torch.eye(5, 5)
eye_tensor

arange = torch.arange(start=0, end=5, step=1)
arange

linspace = torch.linspace(start=0.1, end=1, steps=10)
linspace

x = torch.empty(size=(1,5)).normal_(mean=0, std=1) # verilen ortalama ve standart sapma parametrelerine göre istenen sekilde normal dağılımlı bir tensor  
x

x = torch.empty(size=(1,5)).uniform_(0,1)
x

x = torch.diag(torch.ones(3)) # diagonal matrix oluşturur
x

### Convert Tensor Types

In [ ]:
tensor = torch.arange(4)
print(tensor.dtype)
print(tensor.bool())  # ilk deger 0 oldugu için false verir, geri kalan True

print(tensor.short().dtype) # int16
print(tensor.long().dtype) # int64
print(tensor.half().dtype) # float16
print(tensor.float().dtype) # float32
print(tensor.double().dtype) # float 64

### Array to Tensor or vide-versa convertion

In [ ]:
import numpy as np 
np_array = np.zeros((3,3))
tensor = torch.from_numpy(np_array)
print(tensor)
np_array_back = tensor.numpy()
print(np_array_back)

## Tensor Math operations

In [ ]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

# Toplama
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)
print(z1.dtype)

z2 = torch.add(x, y)
print(z2)
print(z2.dtype)

z = x + y
print(z)
print(z.dtype)

# Çıkarma
z = x - y
print(z)
print(z.dtype)

# Bölme
z = torch.true_divide(x, y) # element-wise division
print(z)
z = x / y
print(z)

# Inplace ops.
t = torch.zeros(3)
print(t)
t.add_(x) # PYTORCH İÇİNDE ..._ ŞEKLİNDE YAZILAN OPERATİONSLAR INPLACE'DİR. YANİ FARKLI BİR KOPYA OLUSTURMADAN DİREK O DEĞİŞKENİN DEĞERİNİ DEĞİŞTİRİRLER.
# add_() fonksiyonu, add() fonksiyonunu inplace olanıdır.
print(t)

# Kuvvet alma
z = x.pow(2)
print(z)
z = x ** 2
print(z)

# karşılaştırma işlemleri
z = x > 0
print(z)

z = x < 0
print(z)

# matrix çarpımı
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

x3 = torch.mm(x1, x2) #2x3 output shape
print(x3)

x3 = x1.mm(x2) #2x3 output shape
print(x3)

# matris kuvveti alma

matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

# element wise çarpım
z = x * y
print(z)

# dot product
z = torch.dot(x, y) # elemnt wise olarak carpım yapar ve cıkan sonucları toplar
print(z)

# BATCH MATRIX MULTIPLICATION
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

out_bmm = torch.bmm(tensor1, tensor2)
out_bmm.shape # (batch, n, p)


## Broadcasting

In [ ]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5)) # bu matrix x1 ile cıkarma işlemine sokulabilmesi için onun shape'ine çevrilir. Yani 1x5 lik satır degeri 5x5 lik haline gelmiş gibi işlem yapılır. 

print(x1)
print(x2)

z = x1 - x2
print(z)

z = x1 ** x2 # element wise olarak x1^^x2 yapılır. shape olarak da yine yukarıdaki işlemin aynısı gerçeklenir
print(z)

## Other Tensor Ops.

In [ ]:
sum_x = torch.sum(x, dim=0) # dim=0 yatay(y ekseni), dim=1 dikey(x ekseni)
print(sum_x)

values, indices = torch.max(x, dim=0)
print(values, indices)

values, indices = torch.min(x, dim=0)
print(values, indices)

abs_x = torch.abs(x) # mutlak deger işlemi

z = torch.argmax(x, dim=0) # bu işlem torch.max ile aynı işlemi yapar fakat FARKI sadece max degerdeki tensorun SADECE İNDİS DEGERINI DÖNDÜRMESİDİR
print(z)

z = torch.argmin(x, dim=0) # bu fonksiyonlar x.min(dim=0) şeklinde de kullanılabilir.
print(z)

mean_x = torch.mean(x.float(), dim=0)  # mean hesabı için pytorch FLOAT DEGER İSTİYOR
print(mean_x)

z = torch.eq(x, y) # iki tensörün degerlernin eşit olup olmamasını karşılaştrır. Eşit ise True, değilse False return eder
print(z)

sorted_y, indices = torch.sort(y, dim=0, descending=False)
print(sorted_y, indices)

z = torch.clamp(x, min=0, max=10) # 0 dan az olan x degerlerinin 0 yapar, 10 dan büyük olan degerleri de 10 yapar. 
print(z)

bool_tensor_ = torch.tensor([1,0,1,1,1], dtype=torch.bool)
print(x)
z = torch.any(bool_tensor_) # bool_tensor_ içinde hiç True degeri var mı ?
print(z)
z = torch.all(bool_tensor_) # bool_tensor_ içindeki bütün degeler True mu ? 
print(z)

## Tensor Indexing

In [ ]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

print(len(x)) # batch sayısı
print(x[0].shape) # 10 tane tensorden ilkini alıyor ve onun shape'ini return ediyor. ---> x[0,:]

print(x[:, 0]) # 10 tane tensorün teker teker hepsinin features degernini alıyor

print(x[2, 0:10]) # 0:10 -->[0,1,2,3,4,5,6,7,8,9]

# fancy indexing
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

x = torch.rand((3, 5))
print(x)
rows = torch.tensor([1, 0]) # x tensoörü üzerinden [1,4] ve [0,0] elemanlarını alır.
cols = torch.tensor([4, 0])

print(x[rows, cols])

# more advanced indexing
x = torch.arange(10)
print(x)
print(x[(x < 2) | (x > 8)]) # | == or. or kullanımı kabul edilimyor.
print(x[x.remainder(2) == 0]) # remainder fonksiyonu mod alma işlemidir. element wise olarak çalışır. Bölümden sonra kalan değeri return eder.

# useful operations
print(torch.where(x > 5, x, x*2)) # x elementleri 5 ten büyükse x degerlerini yaz, büyük degilse 2 ile carpıp yaz. (condition, conditionTrue, conditionFalse)

print(torch.tensor([0,0,1,2,2,3,4]).unique()) # tensor içindeki unique (tek sefer geçen) degerleri alır
print(x.ndimension()) # x'te kac tane dimension oldugunu söyler. x = 5x5x5 tensor olsaydı return edilen dimension degeri 3 olacaktı
print(x.numel()) # tensordeki element sayısını sayar

## Tensor Reshaping

In [234]:
x = torch.arange(9) 
x_3x3 = x.view(3, 3) # contiguous array istiyor.
print(x_3x3)

x_3x3 = x.reshape (3, 3) # contiguous array olmasa da çalışıyor.
print(x_3x3)

y = x_3x3.t() # transpose işlemi. satırlar sütun oluyor.
print(y)
# y.view(9) # hata veriyor
print(y.reshape(9)) # hata vermiyor

"""
C komsuluk tipinde satırlar sırayla farklı memory adreslerinde tutulur. Örneğin [0,1,2], [3,4,5], [6,7,8] farklı memory adreslerinde tutulur.
Bu kısımda view() işlemi yapmada sorun yoktur. Fakat transpose işleminden sonra ortaya cıkan matriste mevcut satırlar önceki memori adreste tutulan satırlardan
farkklı oldugu için view() işlemi gerçekleştirilemez. Çnükü rtık bir komsuluk söz konusu degildir. Bu yüzden view() yerine reshape() kullanılır.
"""

# view işlemi kullanılmak isteniyorsa ise
print(y.contiguous().view(9))


x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

print(torch.cat((x1, x2), dim=0))
print(torch.cat((x1, x2), dim=1))

z = x1.view(-1) # flatten
print(z)

batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1) # batch dimension'unun tut diğerlerini flatten yap !!!
# print(z)
print(z.shape)

# batch degerini tutup (batch,2,5) shape'ini (batch,5,2) haline getirmek için ise;
z = x.permute(0, 2, 1) # 0.dimensionu 0 olarak tutuyoruz, ikinci dimensionu orjinalde indeksi 2 olan 5 degerini getirdik, 3. dimension'a ise orjinal tensorde indeksi 1 olan 2 degeri getirilecek
print(z.shape)

x = torch.ones(3,3)
print(x)
print(x.shape) # 3 3

print(x.unsqueeze(0)) # indeks ile belirtilen noktaya 1 ekler, böylece boyut ve tensörün şekli değişir
print(x.unsqueeze(0).shape) # 1 3 3

print(x.unsqueeze(1)) # indeks ile belirtilen noktaya 1 ekler, böylece boyut ve tensörün şekli değişir
print(x.unsqueeze(1).shape) # 3 1 3

print(x.unsqueeze(2)) # indeks ile belirtilen noktaya 1 ekler, böylece boyut ve tensörün şekli değişir
print(x.unsqueeze(2).shape)


x = torch.zeros(2, 1, 2, 1, 2)
print(torch.squeeze(x, 0)) # tensör içindeki tüm 1 degerleri yok eder, böylece boyut ve tensörün şekli değişir. indeks verildiğinde ise, indeksin tuttugu deger 1 ise onu yok eder, 1 degilse işlem yapmaz.
print(torch.squeeze(x, 0).size())

print(torch.squeeze(x, 1))
print(torch.squeeze(x, 1).size())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
tensor([[0.4247, 0.1286, 0.4273, 0.9628, 0.4274],
        [0.9858, 0.5990, 0.3498, 0.1769, 0.5491],
        [0.2531, 0.6928, 0.4505, 0.7693, 0.4993],
        [0.0584, 0.8086, 0.3179, 0.7064, 0.5459]])
tensor([[0.4247, 0.1286, 0.4273, 0.9628, 0.4274, 0.2531, 0.6928, 0.4505, 0.7693,
         0.4993],
        [0.9858, 0.5990, 0.3498, 0.1769, 0.5491, 0.0584, 0.8086, 0.3179, 0.7064,
         0.5459]])
tensor([0.4247, 0.1286, 0.4273, 0.9628, 0.4274, 0.9858, 0.5990, 0.3498, 0.1769,
        0.5491])
torch.Size([64, 10])
torch.Size([64, 5, 2])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([1, 3, 3])
tensor([[[1., 1., 1.]],

        [